version: "3.8"

services:
  localstack:
    image: localstack/localstack:4.13.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=sa-east-1
      - DEFAULT_REGION=sa-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init:/etc/localstack/init"
      - "./localstack-config/:/opt/custom"
    networks:
      - app-network

  redis:
    image: redis:8.6.3
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge