spring.application.name=sqs-consumer
joinfaces.faces.project-stage=Production
joinfaces.primefaces.theme=saga
joinfaces.primefaces.font-awesome=true
joinfaces.faces-servlet.url-mappings=*.xhtml
joinfaces.faces-servlet.enabled=true
