server.port=3000
spring.application.name=aws-console
joinfaces.faces.project-stage=Production
joinfaces.primefaces.theme=saga
joinfaces.primefaces.font-awesome=true
joinfaces.faces-servlet.url-mappings=*.xhtml
joinfaces.faces-servlet.enabled=true

aws.region=us-east-1
aws.sqs.endpoint=http://localhost:4566

#temas: saga vela arya